import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { closeEvent, deleteEvent, getEvent, publishEvent } from '../services/api'
import { useSession } from '../session/useSession'
import type { EventDetails } from '../types'
import { errorMessage, formatDate } from '../utils'
import { CircleStop, Send } from 'lucide-react'
import { ConfirmModal } from '../components/ConfirmModal'

type PendingAction = 'publish' | 'close'

export function EventDetailPage() {
  const { id } = useParams(); const { session } = useSession(); const navigate = useNavigate(); const [event, setEvent] = useState<EventDetails | null>(null); const [feedback, setFeedback] = useState(''); const [loading, setLoading] = useState(false); const [pendingAction, setPendingAction] = useState<PendingAction | null>(null)
  useEffect(() => { if (!session || !id) return; const currentSession = session; async function load() { try { setEvent(await getEvent(currentSession, Number(id))) } catch (error) { setFeedback(errorMessage(error, 'Não foi possível carregar o evento.')) } } void load() }, [session, id])
  async function remove() { if (!session || !event || !window.confirm('Tem certeza que deseja excluir este evento? Esta ação não pode ser desfeita.')) return; setLoading(true); try { await deleteEvent(session, event.id); navigate('/eventos', { replace: true }) } catch (error) { setFeedback(errorMessage(error, 'Não foi possível excluir o evento.')) } finally { setLoading(false) } }
  async function close() { if (!session || !event) return; setLoading(true); try { setEvent(await closeEvent(session, event.id)) } catch (error) { setFeedback(errorMessage(error, 'Não foi possível encerrar o evento.')) } finally { setLoading(false); setPendingAction(null) } }
  async function publish() { if (!session || !event) return; setLoading(true); try { setEvent(await publishEvent(session, event.id)) } catch (error) { setFeedback(errorMessage(error, 'Não foi possível publicar o evento.')) } finally { setLoading(false); setPendingAction(null) } }
  function confirmAction() { if (pendingAction === 'publish') void publish(); if (pendingAction === 'close') void close() }
  return <section className="detail-view"><Link className="back-button" to="/eventos">← Voltar para eventos</Link>{event ? <><div className="detail-heading"><div><span className="kicker">Detalhes do evento</span><h2>{event.nome}</h2><p>{event.descricao}</p></div><div className="detail-actions">{!event.publicado && !event.encerrado && <button className="action-icon publish-button detail-publish-button" onClick={() => setPendingAction('publish')} disabled={loading} aria-label="Publicar evento" title="Publicar evento"><Send size={16} aria-hidden="true" /></button>}{event.publicado && !event.encerrado && <button className="action-icon close-button detail-close-button" onClick={() => setPendingAction('close')} disabled={loading} aria-label="Encerrar evento" title="Encerrar evento"><CircleStop size={16} aria-hidden="true" /></button>}<Link className="secondary-button" to={`/eventos/${event.id}/editar`}>Editar</Link>{!event.publicado && <button className="danger-button" onClick={() => void remove()} disabled={loading}>Excluir</button>}</div></div><div className="detail-info"><Info label="Quando começa" value={formatDate(event.dataInicio, true)} /><Info label="Quando termina" value={formatDate(event.dataFim, true)} /><Info label="Status" value={event.encerrado ? 'Encerrado' : event.publicado ? 'Publicado' : 'Rascunho'} /><Info label="Local" value={`${event.cidade} / ${event.estado}`} /><Info label="Endereço" value={event.logradouro} /><Info label="CEP" value={event.cep} /></div><section className="ticket-summary"><div className="ticket-summary-heading"><span className="kicker">Ingressos</span><p>Totais e disponibilidade atual por tipo.</p></div><div className="ticket-summary-list">{event.ingressos.map((ticket) => <div className="ticket-summary-row" key={ticket.id}><div><strong>{ticket.tipoIngresso.nome}</strong><small>{formatCurrency(ticket.preco)}</small></div><div><span>Total</span><strong>{ticket.quantidade}</strong></div><div><span>Disponíveis</span><strong>{ticket.disponivel}</strong></div></div>)}</div></section>{pendingAction && <ConfirmModal title={pendingAction === 'publish' ? 'Publicar evento?' : 'Encerrar evento?'} message={pendingAction === 'publish' ? 'O evento ficará disponível como publicado e poderá continuar sendo editado.' : 'O evento será encerrado imediatamente e não poderá voltar ao estado ativo.'} confirmLabel={pendingAction === 'publish' ? 'Publicar' : 'Encerrar'} tone={pendingAction} loading={loading} onConfirm={confirmAction} onCancel={() => setPendingAction(null)} />}</> : <div className="empty-state"><p>{feedback || 'Carregando detalhes...'}</p></div>}</section>
}
function Info({ label, value }: { label: string; value: string }) { return <div className="info-item"><span>{label}</span><strong>{value}</strong></div> }
function formatCurrency(value: number) { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value) }
